### ISSUE TITLE
Terminating the "os1.run_forever()" loop

### ISSUE THREAD

**Issue by SamChuah** [rsiemens/ouster-python#1]
Hi, is there a way to terminate the loop running in the function "run_forever()" rather than just pressing and holding down Ctrl+C until everything stops? 

Thank you.

**Comment by rsiemens** [comment]
Hey @SamChuah. Do you mean programmatically? `run_forever` is just delegating to [socketserver.UDPServer.serve_forever](https://docs.python.org/3.4/library/socketserver.html#socketserver.BaseServer.serve_forever), which can be notified to be shut down with the [shutdown](https://docs.python.org/3.4/library/socketserver.html#socketserver.BaseServer.shutdown) method.

You can access the server instance like...
```
os1 = OS1(OS1_IP, HOST_IP, mode='1024x10')

def handler(raw_packet):
    # do stuff...
    if should_shutdown:
        os1._server.shutdown()

os1.run_forever(handler)
```

Perhaps it would be good to change `_server` to be a public property or expose `shutdown` as a direct method of `OS1`. I just don't want to cause confusion that it doesn't actually shutdown the OS1 device, just the server loop.

Thoughts?

**Comment by SamChuah** [comment]
I managed to kill the loop. But now I am having a problem with loss of data. 
I am trying to write data from every timestamp (1024x64) to a csv file by having 64 workers. However, when I visualize the results, it seems like some CSV files have lost a segment of points.

**Comment by rsiemens** [comment]
Is your device an os16? I noticed I was missing one of the channels for the `xyz_points` and `xyz_columns` functions. Might be unrelated though.

I don't actually have access to the device anymore so I am note able to test. Could this be an issue of dropped packets or is a specific set of points that are always absent?

**Comment by SamChuah** [comment]
I am using os64.
